### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by anthonynorthrup314** [anthonynorthrup314/programation#1]
## General
- [x] Refactor with comments and formatting [{Reference}](https://www.python.org/dev/peps/pep-0008/) [{Reference}](https://www.python.org/dev/peps/pep-0257/)
- [x] Specify external sources in method/class comments

## Changes
- [x] Update README with more information
- [x] Change math with arrays (matrices, points, etc.) [{Reference}](https://docs.scipy.org/doc/numpy-dev/user/numpy-for-matlab-users.html)
- [x] Refactor Transform to use some of the common python operators [{Reference}](https://docs.python.org/2/reference/datamodel.html#emulating-numeric-types)
  - [x] Most importantly `__mul__`
- [x] Change smoothing for Polyline [{Reference}](https://www.particleincell.com/2012/bezier-splines/)
- [x] Change bezier splitting [{Reference}](https://pomax.github.io/bezierinfo/#splitting)

## New Features
- [x] Windows support
- [ ] Create a VectorShape class (consists of only cubic bezier curves)
  - [ ] Create vector versions of all current shapes
    - Use smoothed vector polylines for circular shapes (approximate with angle step)
  - [ ] Add methods for transforming the points
  - [ ] Remove transform properties from Shape class
- [ ] SVG support [{Reference}](https://developer.mozilla.org/en-US/docs/Web/SVG)
  - [ ] Parsing an SVG document [{Reference}](https://docs.python.org/2.7/library/xml.etree.elementtree.html)
  - [ ] Transform support [{Reference}](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/transform)
- [ ] Support for text rendering
  - [ ] Conversion from text to VectorShape
- [x] Saving to video
  - Use ffmpeg [{Reference}](http://zulko.github.io/blog/2013/09/27/read-and-write-video-frames-in-python-using-ffmpeg/)

**Comment by anthonynorthrup314** [comment]
If anyone looking at this project has a suggestion, just leave a comment (links for explanation would be helpful)
